import { cn } from "@/lib/cn";
import StoreProvider from "@/redux/StoreProvider";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import App from "./App";
import Header from "./components/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const barlow_condensed = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={cn(inter.className)}>
				<StoreProvider>
					<App>
						<Header />
						<main className='mx-auto flex max-w-screen-2xl flex-col justify-between px-8 py-12  '>
							{children}
						</main>
					</App>
				</StoreProvider>
			</body>
		</html>
	);
}
